# travis rules for project
language: cpp
compiler:
  - gcc

before_install:
  # intall deps
  - sudo apt-get install -y  libopencv-dev

script: # compile
  - mkdir build
  - cd build
  - cmake ..
  - make
